services:
  backend:
    build: ./backend-servlet
    ports:
      - "8080:8080"
    environment:
      - APP_JWT_SECRET=${APP_JWT_SECRET:-change_this_secret_key_please_change}

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8080
